<a href="https://colab.research.google.com/github/anas1IA/TP_stochastic-process/blob/main/Markov_chani_notes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
A = np.array([[0.95,0.04,0.01,0],[0,0.9,0.05,0.05],[0,0,0.8,0.2],[1,0,0,0]])

In [3]:
A

array([[0.95, 0.04, 0.01, 0.  ],
       [0.  , 0.9 , 0.05, 0.05],
       [0.  , 0.  , 0.8 , 0.2 ],
       [1.  , 0.  , 0.  , 0.  ]])

In [35]:
B = A@A@A@A@A@A@A@A@A@A@A@A@A@A@A@A@A@A@A@A@A@A@A@A@A@A@A@A@A@A@A@A@A@A@A@A@A@A@A@A@A@A@A@A@A@A@A@A@A@A@A@A@A@A@A@A@A@A@A@A@A@A@A@A@A@A@A@A@A@A@A@A@A@A@A@A@A@A@A@A@A@A@A@A@A@A@A@A@A@A@A@A@A@A

In [36]:
32*B

array([[19.99999987,  8.00000009,  3.00000003,  1.00000001],
       [20.00000021,  7.99999974,  3.00000005,  1.        ],
       [20.00000039,  8.00000006,  2.99999964,  0.99999991],
       [19.99999985,  8.00000011,  3.00000003,  1.00000001]])

In [17]:
Pi = B[0,:]
Pi

array([0.62507809, 0.24997268, 0.09371062, 0.03123861])

In [22]:
suM = np.sum(Pi)
suM

0.9999999999999994

In [18]:
R = np.array([900,800,400,0])

In [29]:
Pi*R

array([562.57027682, 199.97814098,  37.48424987,   0.        ])

In [31]:
K = np.sum(Pi*R)
K

800.0326676690291

In [20]:
Pi@R

800.0326676690291

In [41]:
 L = np.array([[0,0,0,0,0,1],[0,0,0,0,0,1],[0,0,0,0,0,1],[0,0,0,0,0,1],[1/10,1/10,2/10,3/10,3/10,0],[0,1/10,1/10,2/10,3/10,3/10]])


In [44]:
C = L@L@L@L@L@L@L@L@L@L@L@L@L@L@L@L@L@L@L@L@L@L@L@L@L@L@L@L@L@L@L@L@L@L@L@L@L@L@L@L@L@L@L@L@L@L@L@L@L@L@L@L@L@L@L@L

In [65]:
Z=149*C
Z

array([[ 3., 10., 13., 23., 30., 70.],
       [ 3., 10., 13., 23., 30., 70.],
       [ 3., 10., 13., 23., 30., 70.],
       [ 3., 10., 13., 23., 30., 70.],
       [ 3., 10., 13., 23., 30., 70.],
       [ 3., 10., 13., 23., 30., 70.]])

In [59]:
Pi =Z[0]


In [62]:
d = Pi*np.array([-2,-1,0,1,2,3])/149


In [63]:
np.sum(d)

1.8590604026845632

In [ ]:
# create  10 pages web( contain the liens that guide un to an other pages ) each page in the case is state (PageRank)
