<a href="https://colab.research.google.com/github/anas1IA/TP_stochastic-process/blob/main/TP_Markov_chaine.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd


In [14]:
P_matrix_transition = np.array([[0,3/4,1/4],
               [1/4,0,3/4],
                [1/4,1/4,1/2]])

In [15]:
A = P_matrix_transition

In [16]:
B=A@A@A@A@A@A@A@A@A@A@A@A@A@A@A@A@A@A@A@A@A@A@A@A@A@A@A@A@A@A@A@A@A@A@A@A@A@A@A@A@A@A@A@A@A@A@A@A@A
25*B

array([[ 5.,  7., 13.],
       [ 5.,  7., 13.],
       [ 5.,  7., 13.]])

In [21]:
Pi_Fes = np.array([1,0,0])
Pi_Tanger = np.array([0,1,0])
Pi_Rabat = np.array([0,0,1])

In [22]:
Pi1_Fes = Pi_Fes@P_matrix_transition
Pi1_Fes

array([0.  , 0.75, 0.25])

In [23]:
Pi1_Tanger  = Pi_Tanger@ P_matrix_transition
Pi1_Tanger

array([0.25, 0.  , 0.75])

In [25]:
Pi1_Rabat = Pi_Rabat@P_matrix_transition
Pi1_Rabat

array([0.25, 0.25, 0.5 ])

In [ ]:
def transition_step(Pi , P ,n = number of steps):
  pass

